/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActivityCardType } from "./global/models/activity-card.model";
import { IButtonEntry } from "./components/button-component/button-component";
import { IFrontPageEntry } from "./components/front-page/front-page";
import { INavbarEntry } from "./components/nav-bar/nav-bar";
import { ISearchEntry } from "./components/search-component/search-component";
import { ratingType } from "./components/stars-component/stars-component";
export namespace Components {
    interface ActivityCard {
        "post": ActivityCardType;
    }
    interface ButtonComponent {
        "buttonEntry": IButtonEntry;
    }
    interface FrontPage {
        "frontPageEntry": IFrontPageEntry;
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface NavBar {
        "navbarEntry": INavbarEntry;
    }
    interface RecentActivity {
        "cards": Array<ActivityCardType>;
        "filterByLocation"?: string;
        "filterByName"?: string;
    }
    interface SearchComponent {
        "searchBarEntry": ISearchEntry;
    }
    interface StarComponent {
        "isSelected": boolean;
        "starSelected": number;
    }
    interface StarsComponent {
        "rating": ratingType;
    }
}
declare global {
    interface HTMLActivityCardElement extends Components.ActivityCard, HTMLStencilElement {
    }
    var HTMLActivityCardElement: {
        prototype: HTMLActivityCardElement;
        new (): HTMLActivityCardElement;
    };
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLFrontPageElement extends Components.FrontPage, HTMLStencilElement {
    }
    var HTMLFrontPageElement: {
        prototype: HTMLFrontPageElement;
        new (): HTMLFrontPageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLRecentActivityElement extends Components.RecentActivity, HTMLStencilElement {
    }
    var HTMLRecentActivityElement: {
        prototype: HTMLRecentActivityElement;
        new (): HTMLRecentActivityElement;
    };
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLStarComponentElement extends Components.StarComponent, HTMLStencilElement {
    }
    var HTMLStarComponentElement: {
        prototype: HTMLStarComponentElement;
        new (): HTMLStarComponentElement;
    };
    interface HTMLStarsComponentElement extends Components.StarsComponent, HTMLStencilElement {
    }
    var HTMLStarsComponentElement: {
        prototype: HTMLStarsComponentElement;
        new (): HTMLStarsComponentElement;
    };
    interface HTMLElementTagNameMap {
        "activity-card": HTMLActivityCardElement;
        "button-component": HTMLButtonComponentElement;
        "front-page": HTMLFrontPageElement;
        "my-component": HTMLMyComponentElement;
        "nav-bar": HTMLNavBarElement;
        "recent-activity": HTMLRecentActivityElement;
        "search-component": HTMLSearchComponentElement;
        "star-component": HTMLStarComponentElement;
        "stars-component": HTMLStarsComponentElement;
    }
}
declare namespace LocalJSX {
    interface ActivityCard {
        "post"?: ActivityCardType;
    }
    interface ButtonComponent {
        "buttonEntry"?: IButtonEntry;
    }
    interface FrontPage {
        "frontPageEntry"?: IFrontPageEntry;
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface NavBar {
        "navbarEntry"?: INavbarEntry;
    }
    interface RecentActivity {
        "cards"?: Array<ActivityCardType>;
        "filterByLocation"?: string;
        "filterByName"?: string;
    }
    interface SearchComponent {
        "onSearchLocationEvent"?: (event: CustomEvent<string>) => void;
        "onSearchPlaceEvent"?: (event: CustomEvent<string>) => void;
        "searchBarEntry"?: ISearchEntry;
    }
    interface StarComponent {
        "isSelected"?: boolean;
        "starSelected"?: number;
    }
    interface StarsComponent {
        "rating"?: ratingType;
    }
    interface IntrinsicElements {
        "activity-card": ActivityCard;
        "button-component": ButtonComponent;
        "front-page": FrontPage;
        "my-component": MyComponent;
        "nav-bar": NavBar;
        "recent-activity": RecentActivity;
        "search-component": SearchComponent;
        "star-component": StarComponent;
        "stars-component": StarsComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "activity-card": LocalJSX.ActivityCard & JSXBase.HTMLAttributes<HTMLActivityCardElement>;
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "front-page": LocalJSX.FrontPage & JSXBase.HTMLAttributes<HTMLFrontPageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "recent-activity": LocalJSX.RecentActivity & JSXBase.HTMLAttributes<HTMLRecentActivityElement>;
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
            "star-component": LocalJSX.StarComponent & JSXBase.HTMLAttributes<HTMLStarComponentElement>;
            "stars-component": LocalJSX.StarsComponent & JSXBase.HTMLAttributes<HTMLStarsComponentElement>;
        }
    }
}
