/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RandomPlace } from "./global/models/randomPlace.model";
export namespace Components {
    interface ButtonComponent {
        "title": string;
        "withBoarder": boolean;
    }
    interface FrontPage {
        "randomPlace": RandomPlace;
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface NavBar {
    }
    interface RecentActivity {
    }
    interface SearchComponent {
    }
}
declare global {
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLFrontPageElement extends Components.FrontPage, HTMLStencilElement {
    }
    var HTMLFrontPageElement: {
        prototype: HTMLFrontPageElement;
        new (): HTMLFrontPageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLRecentActivityElement extends Components.RecentActivity, HTMLStencilElement {
    }
    var HTMLRecentActivityElement: {
        prototype: HTMLRecentActivityElement;
        new (): HTMLRecentActivityElement;
    };
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-component": HTMLButtonComponentElement;
        "front-page": HTMLFrontPageElement;
        "my-component": HTMLMyComponentElement;
        "nav-bar": HTMLNavBarElement;
        "recent-activity": HTMLRecentActivityElement;
        "search-component": HTMLSearchComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonComponent {
        "title"?: string;
        "withBoarder"?: boolean;
    }
    interface FrontPage {
        "randomPlace"?: RandomPlace;
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface NavBar {
    }
    interface RecentActivity {
    }
    interface SearchComponent {
    }
    interface IntrinsicElements {
        "button-component": ButtonComponent;
        "front-page": FrontPage;
        "my-component": MyComponent;
        "nav-bar": NavBar;
        "recent-activity": RecentActivity;
        "search-component": SearchComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "front-page": LocalJSX.FrontPage & JSXBase.HTMLAttributes<HTMLFrontPageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "recent-activity": LocalJSX.RecentActivity & JSXBase.HTMLAttributes<HTMLRecentActivityElement>;
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
        }
    }
}
